# Generated by Django 3.1.1 on 2020-09-24 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professors',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
