# Generated by Django 3.1.1 on 2020-10-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0002_auto_20200923_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='professors',
            name='profile_image',
            field=models.ImageField(default='images/default_profile_image.jpg', upload_to='images/'),
        ),
    ]
