# Generated by Django 3.1.1 on 2020-10-29 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0004_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='professors',
            name='isGraduateAdvisor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.DateTimeField(unique=True),
        ),
    ]
