# Generated by Django 3.1.3 on 2020-11-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0005_auto_20201028_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professors',
            name='isGraduateAdvisor',
            field=models.BooleanField(default=False, verbose_name='Graduate Advisor'),
        ),
    ]
