# Generated by Django 3.1.1 on 2020-11-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0006_auto_20201109_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='professors',
            name='professor_text',
            field=models.TextField(default=' '),
        ),
    ]
