# Generated by Django 3.1.1 on 2020-11-18 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0007_professors_professor_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='professors',
            name='professor_email',
            field=models.EmailField(default='advising.csc.csudh@gmail.com', max_length=254),
        ),
    ]
