# Generated by Django 3.1.1 on 2020-11-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0008_professors_professor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.DateTimeField(unique=True, verbose_name='%a %b %d, %Y %I:%M:%p'),
        ),
    ]
