# Generated by Django 3.1.1 on 2020-11-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0009_auto_20201130_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.DateTimeField(unique=True),
        ),
        migrations.AlterField(
            model_name='professors',
            name='professor_text',
            field=models.TextField(blank=True, default=' '),
        ),
    ]
